### ISSUE TITLE
Spectral normaliation on the attention layer

### ISSUE THREAD

**Issue by zhangmozhe** [taki0112/Self-Attention-GAN-Tensorflow#16]
Hi, I notice in your implementation, there is no spectral normalization for the attention layer. According to the spectral normalization paper, it seems to make more sense to normalize the specral norm of each layer so that the overall Lipschitz constant is less than 1. Therefore, is there any reasons not to do the spectral normalization on the attention layer. Thanks!

**Comment by taki0112** [comment]
It can be adjusted using argparser. The current code uses the spectral norm.
