### ISSUE TITLE
what does "ch" mean?

### ISSUE THREAD

**Issue by codaibk** [taki0112/Self-Attention-GAN-Tensorflow#8]
Hi, I saw you use `ch` variables in generator and discriminator. So could you explain what `ch `means? 
![image](https://user-images.githubusercontent.com/28720676/43315391-6ca9ccf6-91c8-11e8-933d-5e0f2f79032c.png)
![image](https://user-images.githubusercontent.com/28720676/43315425-82fcfc3a-91c8-11e8-8e21-f10dc4e08714.png)

Thanks

**Comment by codaibk** [comment]
Thanks for your reply
so why feature map for generator = 1024? is it related to image size? How if my image input 's size is 256x256. what is value for `ch` i need to put?
Thanks

**Comment by doantientai** [comment]
@codaibk No, feature map does not related to image size. I hope this may help: [https://www.quora.com/What-is-meant-by-feature-maps-in-convolutional-neural-networks](https://www.quora.com/What-is-meant-by-feature-maps-in-convolutional-neural-networks)
